import { cn } from '@/lib/utils';

import { Inter as FontSans } from 'next/font/google';
import localFont from 'next/font/local';
import '@/styles/globals.css';

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' });

const fontHeading = localFont({
  src: '../assets/fonts/CalSans-SemiBold.woff2',
  variable: '--font-heading',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={cn(
          fontSans.variable,
          fontHeading.variable,
          'font-sans antialiased'
        )}
      >
        {children}
      </body>
    </html>
  );
}
